name: syncc_chat_app
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  flutter_spinkit: ^5.2.0
  firebase_storage: ^11.6.0
  image_picker: ^1.0.7
  cloud_firestore: ^4.14.0
  flutter_plugin_android_lifecycle: ^2.0.17
  rflutter_alert: ^2.0.7
  intl: ^0.19.0
  firebase_messaging: ^14.7.10
  firebase_analytics: ^10.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:

  uses-material-design: true

  assets:
     - assets/img/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Italic-VariableFont_wght.ttf
        - asset: assets/fonts/Montserrat-VariableFont_wght.ttf
        - asset: assets/fonts/static/Montserrat-Medium.ttf
        - asset: assets/fonts/static/Montserrat-bold.ttf
        - asset: assets/fonts/static/Montserrat-ExtraBold.ttf

